### ISSUE TITLE
Question about CV2.Circle()

### ISSUE THREAD

**Issue by Raamyy** [Maioy97/IP-practice#1]
Shouldn't the first parameter in the ```cv2.cirlce()``` function be **frame** not **image**?
https://github.com/Maioy97/IP-practice/blob/d0cf90ae28bac2762d2ebf8d3a3ba266e1632f43/featuredetection.py#L19

**Comment by Maioy97** [comment]
oh , you're right 
I must've left it unchanged when I edited the function :D
